### ISSUE TITLE
バグ報告:シェイプキー名がiCyP氏のバージョンから変わってしまっている

### ISSUE THREAD

**Issue by Rikurus** [saturday06/VRM_IMPORTER_for_Blender2_8#3]
**Describe the bug :バグについて**
旧版（iCyP氏）からバージョンアップ後にシェイプ名が変わった関係なのか
CATSプラグインでリップシンク付けるときに前はボタン押すだけでOKだったのが自分で指定する必要が発生するようになりました。（以前はインポート時に自動設定されていたのでボタン押すだけで良かった）

おそらく、シェイプキー名の[Face.M_F00_000_00_Fcl_]の部分が今までのバージョンだと取り払われていたのが今回のバージョンで出てくるようになったことが原因と思われます。
※この結果、Unity側にエクスポートした際にシェイプキーの不一致によりアニメーションファイルの流用などが効かなくなっています

**To Reproduce:バグの再現方法**
VRoid StudioからエクスポートしたVRMモデルにて事象を確認。
（その他の一般的に配布されているVRMモデルでどうなるかは未確認です）

**Expected behavior:期待する動作**
旧版と同じシェイプキー名にて出力するようになってほしいです。
※無理であれば不可能である旨をどこかに記載して欲しい（旧版とは互換性がない旨の掲示）

**Screenshots:スクリーンショット**
ツイッターに添付したのスクリーンショットをご確認ください。
（1枚目が以前の、2枚目が現在のシェイプキー名になります）
https://twitter.com/rikurus/status/1269543987343273987

**Desktop (please complete the following information):PC環境情報**
Windows 10
Blender 2.83
VRM_IMPORTER_for_Blender2_8-0_83_0

**Additional context :なにか他に書いておきたいことはこちらへ**
いつもメンテナンスお疲れさまです。
無理はせずゆっくり取り組んでくださいませ！(∩´∀`)∩

**Comment by saturday06** [comment]
iCyPさんの最終バージョン0.79とBlender 2.82aの組み合わせでVRoidStudio0.95製のVRMファイルをインポートしたところ、シェイプキー「Face.M_F00_000_00_Fcl_」の削除は行われていませんでした。また、そのファイルをVRMエクスポートしてUnityで閲覧したところ、同様にシェイプキー「Face.M_F00_000_00_Fcl_」の削除は行われていませんでした。

# iCyPさんの最終バージョン0.79でVRMファイルを読み込んだスクショ
![icyp](https://user-images.githubusercontent.com/532872/83968456-710f1a80-a904-11ea-89dd-7801326cf4a9.PNG)

# iCyPさんの最終バージョン0.79でエクスポートしたVRMファイルをUnityで閲覧したスクショ
![icyp-vroid2](https://user-images.githubusercontent.com/532872/83968529-e0850a00-a904-11ea-8ee2-f5e97cb90a03.png)

そのため、iCyPさんの最終バージョンからシェイプキー関連の変更は行われていないことが確認できます。

**Comment by saturday06** [comment]
そのため、ご利用の正常動作が確認できているiCyPさんのBlenderプラグインのバージョンを教えていただけますでしょうか？

**Comment by saturday06** [comment]
私のプラグインのバージョン0.83.0とBlender 2.83.0の組み合わせで、cats-blender-pluginのFix Modelボタンを押したところ、所望のシェイプキーが得られたように見えます。ご確認ください。問題が解決しない場合は、VRMファイルをtwitterのDMなどでお送りただければと思います。

![fix](https://user-images.githubusercontent.com/532872/83969017-2bece780-a908-11ea-8ae2-1bed1cf6d499.png)

**Comment by saturday06** [comment]
以前、ノーマルマップの件でcats-blender-pluginとの連携不具合が発生したプラグインをお使いだったと思います。その状態のプラグインでインポートした状態のモデルに対しては、cats-blender-pluginのFix Modelボタンが正常動作しないという可能性があります。

そのため、問題が解決しない場合は、申し訳ないのですがVRMをBlenderへインポートをするところから再度試していただきたいです。

**Comment by Rikurus** [comment]
ご確認および報告して頂きありがとうございます！！
私はVRMのインポートをする際に『**CATSプラグイン上に存在するインポートボタン**』を使ってインポートを行っていたのですが、これが原因でシェイプキーがおかしくなっていたようです。

saturday様のVRM_IMPORTERを導入後、『**Blenderのファイルメニューからインポートを行った**』場合、欲しかったシェイプキーの名称で無事にインポートが行えました。

恐らく（？）、『CATSプラグイン上のインポートボタン（こちらはVRM_IMPORTERを使っていない？）』と『Blenderのファイルメニューからのインポート（こちらはsaturday様のVRM_IMPORTERの機能を使う）』で処理に違いが起きており、それが原因で発生していたものと思われます。
ご丁寧に確認して頂きありがとうございました。

**Comment by saturday06** [comment]
調査の結果、本事象はcatsプラグイン最新版0.17.0で入った仕様変更かバグでした。そのため、もしワークフローを変えることができない場合はcatsプラグインを0.16.1にダウングレードすることで対応することも可能です。次回も何かあったらよろしくお願いします！ 🙏

**Comment by Darkblader24** [comment]
Hey, cats dev here. Are you sure this is a cats bug introduced in 0.17.0? I haven't changed anything regarding vrm shapekeys, at least not that I know.

Also I will fix the typo in the material fix in cats in future versions. But don't fix that now, only when I release the next cats version.

**Comment by saturday06** [comment]
Thanks your followup. I'll create new issue https://github.com/michaeldegroot/cats-blender-plugin/issues with reproducing steps. Please wait a while.

**Comment by saturday06** [comment]
> Also I will fix the typo in the material fix in cats in future versions. But don't fix that now, only when I release the next cats version.

Thanks a lot!!!!!!!! ❤️❤️❤️❤️❤️❤️

**Comment by saturday06** [comment]
Issue created https://github.com/michaeldegroot/cats-blender-plugin/issues/191
