### ISSUE TITLE
Amature直下にRoot以外のボーンが作られることについて Feature request:要望

### ISSUE THREAD

**Issue by JunKuro** [saturday06/VRM_IMPORTER_for_Blender2_8#4]
・環境
win7 64bit
blender ver2.83.4
VRM_IMPORTER ver0.93.1

**Is your feature request related to a problem? Please describe.:バグじゃないけどアドオンの動作でなにか困ってることがあれば**

VRoidStudio ver0.11.1でマテリアルを統合してエクスポートしたVRMファイルをインポートすると
Amature直下にsecondaryがボーンとして作られる場合があるみたいで
そのままでエクスポートしようとするとrootボーンと競合するといったようなエラーが発生します

**Describe the solution you'd like:どう動いてほしいかをどうぞ**

secondaryボーンが作られないようになると嬉しいです
（secondaryボーン削除後にエクスポートしたVRMファイルをUnityで確認した限りではsecondaryやスプリングボーンのコンポーネントは問題無さそう？だったので

**Comment by saturday06** [comment]
ご要望ありがとうございます。報告していただいた事象を私の手元で再現することができました。インポート時に必要に応じてsecondaryを除外する処理を追加します。

**Comment by saturday06** [comment]
VRMの仕様を見たのですが「複数のrootボーンが許可されない」との記述は見つからなかったので、エクスポート時の競合チェック自体をやめてエラーにならないようにします。

Blenderプラグインとしては、もともとのデータに含まれていたものはできるだけ削除したくない、というのもあります。不要な孤立したボーンがある場合はBlender上で削除できるので。

**Comment by saturday06** [comment]
プラグインバージョン 0.94.0 ( https://github.com/saturday06/VRM_IMPORTER_for_Blender2_8/archive/0_94_0.zip ) でエクスポート時にエラーにならないように修正しました。依然エラーが発生する場合や、今回の修正方式ではダメそうな場合このイシューを再オープンお願いします。
